mesa: Test for linking with libatomic.
Fix build errors on platforms that require libatomic.  Notably this
is seen on the Raspberry Pi Zero family with errors such as:

    glsl/.libs/libstandalone.a(libmesautil_la-disk_cache.o): In function `evict_lru_item':
    /usr/src/debug/mesa-gl/2_17.1.7-r0/mesa-17.1.7/src/util/disk_cache.c:615: undefined reference to `__atomic_fetch_add_8'
    glsl/.libs/libstandalone.a(libmesautil_la-disk_cache.o): In function `cache_put':
    /usr/src/debug/mesa-gl/2_17.1.7-r0/mesa-17.1.7/src/util/disk_cache.c:886: undefined reference to `__atomic_fetch_add_8'
    glsl/.libs/libstandalone.a(libmesautil_la-disk_cache.o): In function `disk_cache_remove':
    /usr/src/debug/mesa-gl/2_17.1.7-r0/mesa-17.1.7/src/util/disk_cache.c:637: undefined reference to `__atomic_fetch_add_8'
    collect2: error: ld returned 1 exit status

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>